### ISSUE TITLE
Update to reflect on-prem to on-prem

### ISSUE THREAD

**Issue by tansley-netapp** [NetAppDocs/bluexp-disaster-recovery#21]
### Page URL

https://docs.netapp.com/us-en/bluexp-disaster-recovery/get-started/dr-setup.html

### Page title

Set up your infrastructure for BlueXP disaster recovery

### Summary

A-M,

This page seems to only be focused on configuring BlueXP DR for on-prem to AWS. Are there plans to update this?

Tony

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by amgrissino** [comment]
Meeting set for Nov 19 to discuss.

**Comment by amgrissino** [comment]
Working on changes.

**Comment by amgrissino** [comment]
Changes published live. Thank you @tansley-netapp !! Closing this.
